//Devco users
export  const S_LOGIN = "S_LOGIN"
export  const F_LOGIN = "F_LOGIN"
export  const S_REGISTER = "S_REGISTER"
export  const F_REGISTER = "F_REGISTER"
export  const S_USER_INFO = "S_USER_INFO"
export  const F_USER_INFO = "F_USER_INFO"
export  const S_USER_PROFILE = "S_USER_PROFILE"
export  const F_USER_PROFILE = "F_USER_PROFILE"
export  const S_UPDATE_PROFILE = 'S_UPDATE_PROFILE'
export  const S_LOGOUT = "S_LOGOUT"
export  const F_LOGOUT = "F_LOGOUT"

// Topics and feeds

export const S_GET_TOPICS = "S_GET_TOPICS"
export const F_GET_TOPICS = "F_GET_TOPICS"

export const S_POST_TOPICS = "S_POST_TOPICS"
export const F_POST_TOPICS = "F_POST_TOPICS"

export const S_GET_FEEDS = "S_GET_FEEDS"
export const F_GET_FEEDS = "F_GET_FEEDS"

export const S_GET_FEED = "S_GET_FEED"
export const F_GET_FEED = "F_GET_FEED"

export const S_POST_LIKE_COMMENT = "S_POST_LIKE_COMMENT"
export const F_POST_LIKE_COMMENT = "F_POST_LIKE_COMMENT"

export const S_POST_REPLIES = "S_POST_REPLIES"
export const F_POST_REPLIES = "F_POST_REPLIES"
export const F_GET_TOPIC_COUNT = "F_GET_TOPIC_COUNT"
export const S_GET_TOPIC_COUNT = "S_GET_TOPIC_COUNT"
export const S_POST_SAVES = "S_POST_SAVES"
export const F_POST_SAVES = "F_POST_SAVES"
export const S_POST_LIKES = "S_POST_LIKES"
export const F_POST_LIKES = "F_POST_LIKES"
export const S_POST_FEED = "S_POST_FEED"
export const F_POST_FEED = "F_POST_FEED"
export const S_FOLLOW = "S_FOLLOW"
export const F_FOLLOW = "F_FOLLOW"
export const S_GET_TRENDING = "S_GET_TRENDING"
export const F_GET_TRENDING = "F_GET_TRENDING"
export  const S_GET_RECOMMENDED_PROFILES = "S_GET_RECOMMENDED_PROFILES"
export  const F_GET_RECOMMENDED_PROFILES = "F_GET_RECOMMENDED_PROFILES"
export const S_FOLLOWING_ME = "S_FOLLOWING_ME"
export const F_FOLLOWING_ME = "F_FOLLOWING_ME"
export const S_I_FOLLOW = "S_I_FOLLOW"
export const F_I_FOLLOW = "F_I_FOLLOW"
export const S_MY_LIKES = "S_MY_LIKES"
export const F_MY_LIKES = "F_MY_LIKES"
export const S_MY_SAVINGS = "S_MY_SAVINGS"
export const F_MY_SAVINGS = "F_MY_SAVINGS"
export const S_DELETE_MY_POST = "S_DELETE_MY_POST"
export const F_DELETE_MY_POST = "F_DELETE_MY_POST"
export const S_EDIT_MY_POST = "S_EDIT_MY_POST"
export const F_EDIT_MY_POST = "F_EDIT_MY_POST"
export const S_EDIT_MY_PROFILE = "S_EDIT_MY_PROFILE"
export const F_EDIT_MY_PROFILE = "F_EDIT_MY_PROFILE"
export const S_HIS_PROFILE = "S_HIS_PROFILE"
export const F_HIS_PROFILE = "F_HIS_PROFILE"
export const S_GET_NOTIFICATIONS = "S_GET_NOTIFICATIONS"
export const F_GET_NOTIFICATIONS = "F_GET_NOTIFICATIONS"
export const S_READ_NOTIFICATIONS = "S_READ_NOTIFICATIONS"
export const F_READ_NOTIFICATIONS = "F_READ_NOTIFICATIONS"
